# Generated by Django 4.2.16 on 2024-10-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='nim',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='nip',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
